name: Run BDD Tests

on:
  push:
    branches:
      - bdd-tests
  pull_request:
    branches:
      - bdd-tests

jobs:
  bdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        run: npm install --save-dev @cucumber/cucumber

      - name: Run BDD tests
        run: npx cucumber-js
